# Generated by Django 4.2.11 on 2024-04-05 13:37

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_remove_category_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='embvideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400, null=True)),
                ('link', embed_video.fields.EmbedVideoField()),
                ('description', models.TextField()),
            ],
        ),
    ]
