# Generated by Django 4.2.11 on 2024-04-22 16:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0004_alter_posts_postdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='postdetails',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
