# Generated by Django 5.0.4 on 2024-06-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0006_alter_posts_postdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='status',
            new_name='SinglePageTrending',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='trending',
        ),
        migrations.AddField(
            model_name='posts',
            name='Trending',
            field=models.BooleanField(default=False, help_text='0-show,1-Hidden'),
        ),
    ]
